services:
  node:
    container_name: backend
    build: ./backend
    working_dir: /home/node/app
    ports:
      - '3001:3001'
    volumes:
    - './backend/src:/home/node/app/src'
    # - '/home/node/app/node_modules' 
    links:
      - mongo
  mongo:
    container_name: database
    image: 'mongo:latest'
    ports:
      - '27017:27017'